# Generated by Django 6.0.3 on 2026-09-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='animais', verbose_name='Foto')),
                ('mais_informacoes', models.TextField(verbose_name='Mais informações...')),
                ('idade_aproximada', models.CharField(max_length=50, verbose_name='Idade Aproximada')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível para adoção'), ('ADOTADO', 'Adotado')], default='DISPONIVEL', max_length=10, verbose_name='Status')),
                ('especie', models.CharField(max_length=50, verbose_name='Espécie')),
                ('sexo', models.CharField(choices=[('MACHO', 'Macho'), ('FEMEA', 'Fêmea')], max_length=10, verbose_name='Sexo')),
                ('porte', models.CharField(choices=[('PEQUENO', 'Pequeno'), ('MEDIO', 'Médio'), ('GRANDE', 'Grande')], max_length=10, verbose_name='Porte')),
                ('vacinado', models.BooleanField(default=False, verbose_name='Vacinado')),
                ('castrado', models.BooleanField(default=False, verbose_name='Castrado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('adotado_em', models.DateTimeField(verbose_name='Adotado em')),
            ],
        ),
    ]
