# Generated by Django 6.0.3 on 2026-09-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animais', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='mais_informacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Mais informações...'),
        ),
    ]
