# Generated by Django 6.0.3 on 2026-09-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_animal_foto_alter_animal_mais_informacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adotado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Adotado em'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='mais_informacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Mais informações'),
        ),
    ]
