# Generated by Django 6.0.3 on 2026-09-15 00:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_animal_adotado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='especie',
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animais', validators=[app.models.validar_tamanho_foto], verbose_name='Foto'),
        ),
    ]
